# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10)),
                ('brand', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10)),
                ('model', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10)),
                ('year_min', models.IntegerField(blank=True, null=True)),
                ('year_max', models.IntegerField(blank=True, null=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('location', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('category_id', models.CharField(max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('start_time', models.CharField(max_length=40)),
                ('stop_time', models.CharField(max_length=40)),
                ('permalink', models.URLField(max_length=500)),
                ('thumbnail', models.URLField(max_length=500)),
                ('last_updated', models.CharField(max_length=40)),
                ('alerts', models.ManyToManyField(to='alertas.Alert')),
            ],
        ),
    ]
