# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0004_auto_20160623_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='mileage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
